### ISSUE TITLE
NodeData and MeasureFunc are not thread-safe

### ISSUE THREAD

**Issue by colepoirier** [DioxusLabs/taffy#146]
## What problem does this solve or what need does it fill?

"I am implementing a UI layer in an async framework, and I am unable to pass Stretch around (including using it as a member on the "self" structure) in async code because MeasureFunc is not Send/Sync."

https://github.com/DioxusLabs/taffy/blob/59a8e27c9ba5faa67feb8652180dd4981a6311a0/src/node.rs#L21

## What solution would you like?

"I believe that the change may be as simple as changing the type of Boxed's value to sys::Box<dyn Fn(Size<Number>) -> Size<f32>> + Send + Sync)"

"This, unfortunately, could be a breaking change since this is a publicly exposed enum, so before jumping in to create a PR, I wanted to see what the opinion would be of attempting this change. I'm new enough to understanding how async works that I am not sure what the likelihood that these functions in most codebase wouldn't already be Send + Sync."

## What alternative(s) have you considered?

N/A

## Additional context

Migrating from https://github.com/vislyhq/stretch/issues/69.

Because this is a migration of an issue, I am reproducing the original using direct quotations (indicated using "..") from the original issue author @ecton but modifying the url to point to taffy code.

**Comment by alice-i-cecile** [comment]
Thanks! I think the easiest and best solution to this is actually just to remove `MeasureFunc` completely, per #101.

**Comment by colepoirier** [comment]
> Thanks! I think the easiest and best solution to this is actually just to remove `MeasureFunc` completely, per #101.

Great! I guess the pr for that should reference this issue so it closes once it is merged?

**Comment by alice-i-cecile** [comment]
Yes, exactly.

**Comment by alice-i-cecile** [comment]
So, looking at this further. The crux of the matter is that ` MeasureFunc::Raw(fn(Size<Option<f32>>) -> Size<f32>),` is simply not thread-safe.

It's a [raw function pointer](https://doc.rust-lang.org/core/primitive.fn.html), there's no way to add trait bounds because it's just an object.

Ordinarily we'd bypass this by using a trait object, as discussed more in #101. Unfortunately we *can't* just do this, because this type is deliberately heap-free: we can't use a `Box<dyn Measurable>` that has the required `Send + Sync` trait bounds like you normally would.

We have the following constraints:
1. The library must work in async and parallel code, and thus all data must be `Send + Sync`.
2. There must be an allocation-free path through the code.
3. We need to be able to specify a way by which by nodes can set their intrinsic size using a measure function.

There are a few paths forward:

1. Remove `MeasureFunc` completely without providing a replacement. Dead easy, but it seems like it might be useful?
2. Remove `MeasureFunc` for the allocation free path. Just store a `Box<dyn Measurable>` with the correct bounds in `NodeData`.
3. Wrap the raw function pointer in an `Arc` or the like to make it thread-safe, and then add the appropriate trait bound to the boxed variant.

I'm going to poke at 3, and see what we can do.
