### ISSUE TITLE
Unit test `Forest`

### ISSUE THREAD

**Issue by Weibye** [DioxusLabs/taffy#176]
## What problem does this solve or what need does it fill?

`Forest` should have unit-tests. It does not currently have any.

## What solution would you like?

Add tests to `forest` covering all its methods

**Comment by mcrvaz** [comment]
So, I've been trying to tackle this but right now I'm running into some issues.
As Alice pointed out [here](https://github.com/DioxusLabs/taffy/issues/101#issuecomment-1153088574), this crate is supposed to work in an allocation-free environment, I'm not sure why though, would love to know the reason. But this seems to conflict with creating nodes with multiple parents since `new_leaf` and `new_leaf_with_children` are created with capacity for only a single parent. 
Actually as I was writing this I've just noticed that there's a hard coded limit (1) for the number of parents in these environments and this leads me to some questions:

- Is it useful to have multiple parents? Is this behaviour observed in the codebase?
- Should every environment have the same features? If so, should we have tests that target each environment individually?

**Comment by alice-i-cecile** [comment]
> As Alice pointed out https://github.com/DioxusLabs/taffy/issues/101#issuecomment-1153088574, this crate is supposed to work in an allocation-free environment, I'm not sure why though, would love to know the reason.

Me too!  This was inherited.I presume this was useful for some downstream consumers the original library had; possibly for FFI or on very limited hardware?

> Is it useful to have multiple parents? Is this behaviour observed in the codebase?

Nodes should never have multiple parents. This actually deserves its own issue I think; this is a logic bug no matter what features we have.

> Should every environment have the same features? If so, should we have tests that target each environment individually?

Tests should pass under all combinations of settings. We should aim to minimize divergence wherever possible, including in tests.
