### ISSUE TITLE
Return iterator instead of vector of children

### ISSUE THREAD

**Issue by bestouff** [DioxusLabs/taffy#222]
## `taffy` version

0.2.0 from git before release

## Platform

Rust

## What you did

I just read the doc.

## What went wrong

`Taffy::chlidren()` returns a `Vec<Node>`, which means it has to allocate some memory and duplicate the children ids. I guess this is done to simplify the lifetimes handling when interfacing with other languages.  
Anyway would it be possible to have a method returning an iterator on children instead ? From a Rust pov it'd be more efficient.

**Comment by nicoburns** [comment]
This PR (https://github.com/DioxusLabs/taffy/pull/202) changes `chidlren()` to return `&[Node]` (and also abstracts storage behind a trait so that you can provide your own if you so wish). Would that be acceptable to you? (note that Node is just an id, which needs to be looked up separately to get the actual node data, so mutability is not needed)

**Comment by bestouff** [comment]
That would be very nice yes. I'm leaving more comments in the PR.

**Comment by nicoburns** [comment]
Fixed (children now returns `&[Node]` by #238

**Comment by geom3trik** [comment]
This may not apply to Taffy (because I think it has its own tree representation?) but returning `&[Node]` requires that the child elements be contiguous. It's possible to represent a tree using links to a 'first child' and 'next sibling', in which case the children themselves are not stored contiguously. For this case returning an iterator would be the only solution I think.

**Comment by bestouff** [comment]
Nice, thanks !

**Comment by nicoburns** [comment]
> This may not apply to Taffy (because I think it has its own tree representation?) but returning &[Node] requires that the child elements be contiguous. It's possible to represent a tree using links to a 'first child' and 'next sibling', in which case the children themselves are not stored contiguously. For this case returning an iterator would be the only solution I think.

Indeed. I think this is somewhat mitigated in Taffy by the fact that `children()` doesn't return the node data itself (which is in a struct called `NodeData`), but merely the id/key which represents it (`Node`). I personally feel like this naming is quite confusing and it should be `NodeId`/`Node` rather than `Node`/`NodeData`, but I think it makes this API less problematic.

**Comment by geom3trik** [comment]
> > This may not apply to Taffy (because I think it has its own tree representation?) but returning &[Node] requires that the child elements be contiguous. It's possible to represent a tree using links to a 'first child' and 'next sibling', in which case the children themselves are not stored contiguously. For this case returning an iterator would be the only solution I think.
> 
> Indeed. I think this is somewhat mitigated in Taffy by the fact that `children()` doesn't return the node data itself (which is in a struct called `NodeData`), but merely the id/key which represents it (`Node`). I personally feel like this naming is quite confusing and it should be `NodeId`/`Node` rather than `Node`/`NodeData`, but I think it makes this API less problematic.

What I was saying before still applies if the nodes are just IDs. So in my GUI lib I use IDs as well and store the tree as a sparse set of `first_child` and `next_sibling`. This allows the tree to be represented in a very cache friendly way where each node can have one first child (or none) and one next sibling (or none). What this means is that to iterate on the children the iterator has to first get the ID of the first child and then repeatedly get the ID of the next sibling. I'm just providing this explanation as an example of where the children are not contiguous and thus I'm not even sure if it's possible for such a tree representation to return `&[NodeId]`. However, it could be argued that because these IDs tend to be trivially copyable, the performance impact of returning `&[NodeId]` (if that's even possible) could be negligible.

**Comment by geom3trik** [comment]
To add to the above. The way I get around this in morphorm is to provide an associated type which implements `Iterator`, which can then be specified by the user who is providing their own tree representation. I also think there is a way to make this work when the node isn't just an ID, but actually stores its children and style properties, using GATs. But I haven't had a chance to try this yet.
