### ISSUE TITLE
Expose `border` calculated value

### ISSUE THREAD

**Issue by afonsolage** [DioxusLabs/taffy#223]
## What problem does this solve or what need does it fill?

Currently `Taffy` uses `border` as a second `margin`, which is just used to compute inner margin of children. If some crate want to draw borders `Taffy` doesn't tell where the border begins and where it ends, which forces crate users to recalculate `border` by hand.

## What solution would you like?

Expose the computed `border` value, so users can differentiate between `padding` (external), `border` (middle) and `margin` (internal)

## What alternative(s) have you considered?

Computing `border` by hand, which is very error prone.

## Additional context

In fact `border` isn't part of `Flex`, it's more likely part of `CSS` specification which is used to draw fancy borders on documents, but since `Taffy` already supports `border` (in fact [`border-width`](https://www.w3schools.com/cssref/pr_border-width.asp)), it would be a nice feature to expose this to users than can actually draw their borders.

**Comment by Weibye** [comment]
I agree, and I think we should expose all intermediate values so that it is possible to construct debugger tools on top of `taffy` that would be able to inspect "user desired sizes" vs "what the layouting engine output"

Tools like this:
![image](https://user-images.githubusercontent.com/13300393/187191882-1a2aa2af-2b16-4e9c-9228-665666d69d10.png)
![image](https://user-images.githubusercontent.com/13300393/187192035-ca9e5e24-6a61-4f47-a14b-06a010c9d5a4.png)

**Comment by nicoburns** [comment]
I'm now of the opinion that we should just bite the bullet on the increased memory usage, and expose this information (border, margin, and padding). I think this ought to be quite straightforward. I reckon the only tricky part will be ensuring that the values are rounded correctly.
