### ISSUE TITLE
Combination of flex-direction & height breaks measure function

### ISSUE THREAD

**Issue by adjabaev** [DioxusLabs/taffy#353]
## `taffy` version

0.3.0 alpha 1 (current main)

## Platform

Rust

## What you did

```html
<div id="test-root" style="display: flex; flex-direction: column; width: 100px; height: 100px;">
<div>HHHHHHH&ZeroWidthSpace;HHHHHH&ZeroWidthSpace;HHHH&ZeroWidthSpace;HHHHHH&ZeroWidthSpace;HHHH&ZeroWidthSpace;HHHHHHH</div>
</div>
```

## What went wrong

Test doesn't pass

**Comment by nicoburns** [comment]
I think this is related to #351.

The following shorter snippet has the same problem (in general you are unlikely to need more than one `&ZeroWidthSpace` because that's sufficient to make the min-content size and the max-content size different):

```html
<div id="test-root" style="display: flex; flex-direction: column; width: 100px; height: 100px;">
    <div>HH&ZeroWidthSpace;HH</div>
</div>
```
It also fails without the explicit width/height, which I suspect is the same bug, but I'm not sure.
```html
<div id="test-root" style="display: flex; flex-direction: column">
    <div>HH&ZeroWidthSpace;HH</div>
</div>
```

**Comment by nicoburns** [comment]
It turns out even the following fails (and it fails with both `flex-direction: row` and `flex-direction: column`):

```html
<div id="test-root">
  HH&ZeroWidthSpace;HH
</div>
```

So this is definitely #351. If I rememeber correctly, content sizing of items with min-content and max-content sizes that are not equal to each other has never worked for the flexbox algorithm, and I noted this when I first extended the test generator to do content-sizing of text, but I was focussed on CSS Grid at that time and decided to leave that issue until later. I guess now's the time!
