### ISSUE TITLE
LengthPercentageAuto v.s. Dimension

### ISSUE THREAD

**Issue by SimonSapin** [DioxusLabs/taffy#442]
These two enums appear to be identical:

* https://docs.rs/taffy/0.3.11/taffy/style/enum.LengthPercentageAuto.html
* https://docs.rs/taffy/0.3.11/taffy/style/enum.Dimension.html

Am I missing something, or could one of them potentially be removed?

**Comment by SimonSapin** [comment]
(This isn’t quite a bug, please set labels as appropriate)

**Comment by nicoburns** [comment]
You're correct that they're currently the same. Both exist because it's anticipated that they will diverge in future. Specifically we intend to add values such `MinContent`, `MaxContent`, `FitContent` and `Stretch` to `Dimension` (which is used for `width`, `height`, etc), whereas `LengthPercentageAuto` (which is used for `margin` and `inset`) is not anticipated to gain extra values.

**Comment by SimonSapin** [comment]
That makes sense, thanks!
