### ISSUE TITLE
Proper min_height relative to parent

### ISSUE THREAD

**Issue by jrmoulton** [DioxusLabs/taffy#488]
## `taffy` version

taffy v0.3.12

## Platform

MacOS / floem

## What you did

I had a node that has I was setting min height on and (as best I can tell) when requesting the height of the node directly it was correctly reported but when requesting the height of the node relative to a parent node it incorrectly reported the height and didn't account for the min height. In floem the element itself was painted with the proper height but when the parent requested the height of the child node relative to it using a Taffy.layout(child) it was incorrect. When I set both the min_height and the height to the same value then the issue was resolved. I believe this is related to #407

**Comment by nicoburns** [comment]
@jrmoulton Do you have an actual code example of the problematic behaviour? I'm finding hard to understand exactly what the problem is (and also to determine whether it's a genuine bug, or just css being unintuitive) from your description. Floem code would be acceptable.

Often the easiest way to create a reproduction if you don't already have runnable sample code is to clone the Taffy repo and then create a new test fixture in the `text_fixtures/` directory (this is just an HTML file). You can open that in a browser to play around with how browsers layout different style combinations, and it is also possible to automatically generate a test case which will compare the layout that Taffy produces with the layout that Chromium produces (see https://github.com/DioxusLabs/taffy/blob/main/CONTRIBUTING.md#running-tests)

**Comment by jrmoulton** [comment]
Ahh the testing/comparing would be  really useful. Thanks for the link. I'll start there
