### ISSUE TITLE
`taffy::leaf::compute` is exported as `taffy::compute::compute`

### ISSUE THREAD

**Issue by vkurchatkin-miro** [DioxusLabs/taffy#559]
## `taffy` version

9e62e959cb49f18f8b452f0dd1a9c7adb8dd02cb

## Platform

WASM

## What you did

I'm trying to implement `LayoutTree` and there is seemingly no better way than to copy `Taffy` and change to work with existing data structure. One small bump using this approach: module `taffy::compute::leaf` is private. There seems to be no good reason for that. Luckily, only `taffy::compute::leaf::compute` is required, but it is exposed as `taffy::compute::compute` which is probably unintended. 

## What went wrong

N/A

## Additional information

As an alternative idea/question: why not have leaf as a `LayoutAlgorithm`?  `MeasureFunc` can become a method on `LayoutTree` instead

**Comment by alice-i-cecile** [comment]
Can you please open a PR to make the required module public and fix the re-export?

**Comment by nicoburns** [comment]
@vkurchatkin-miro The immediate issue of leaf layout not being exported properly was fixed in #562. However, I've also done a much more extensive refactor of Taffy's low-level API (for using Taffy with custom trees), and added examples in #564. What do you think?

> As an alternative idea/question: why not have leaf as a LayoutAlgorithm? MeasureFunc can become a method on LayoutTree instead

The plan is actually to go the other way and remove the `style` method from `LayoutAlgorithm`, and have separate `FlexboxLayoutAlgorithm`, etc traits that inherit from `LayoutAlgorithm` and add the style methods back in. That way Taffy can be extended to work with layout algorithms that use completely different style inputs. You are expected to "dispatch" to the different layout algorithms in your implementation of the `compute_child_layout` function (see examples in #564)

**Comment by vkurchatkin-miro** [comment]
> What do you think?

Love it. Seems to open up some optimization possibilites. `custom_layout_tree_owned.rs` relies on unsafe which would be really nice to avoid. Although I can't think of this approach to be usable in general because of numerous limitations.

> t inherit from LayoutAlgorithm and add the style methods back in

This is fine by me as well. Also one more idea here - make `Style` a trait. Currently I have my own style struct and have to keep taffy's style in sync with it
