### ISSUE TITLE
Grid alignment issue with auto tracks

### ISSUE THREAD

**Issue by akesson** [DioxusLabs/taffy#624]
## `taffy` version

0.4.0

## Platform

Rust

## What you did

https://github.com/akesson/taffy-issue

## What went wrong

<img width="1306" alt="taffy" src="https://github.com/DioxusLabs/taffy/assets/1822029/30f6709a-48b6-4b16-8c5d-297cd185649f">

**Comment by nicoburns** [comment]
I am able to reproduce this as a generated test with the following HTML snippet:

```html
<div id="test-root" style="display: grid; width: 320px; height: 640px; grid-template-columns: auto auto 1fr; grid-template-rows: auto auto auto 1fr; justify-content: start; justify-items: start;">
  <div style="background: #59c4f6; width: 100px; height: 50px; grid-row: 1 / span 2; grid-column: 1;"></div>
  <div style="background: #63c466; width: 40px; height: 30px; grid-row: 1 / span 2; grid-column: 2 / span 2;"></div>
  <div style="background: #feb43f; width: 120px; height: 20px; grid-row: 3 / span 1; grid-column: 1 / span 2;"></div>
</div>
```

If I am understanding correctly, then the blue (top left) and green (top right) nodes place correctly when the yellow (bottom) node is not present, but when the yellow node is added to the grid then the green node is incorrectly places 10px to the right of where it should be.

I haven't had a chance to dig into this in detail yet, but I strongly suspect that this is because the yellow node is causing the 1 grid column to be sized 10px too large. The yellow node is 20px larger than the first column, which if shared evenly across the two columns would make the first column 10px larger. This shouldn't happen because the second column (which it also spans) already has enough space for the extra width, but I suspect that there is bug causing it to happen anyway.

**Comment by nicoburns** [comment]
I've opened https://github.com/w3c/csswg-drafts/issues/10095 to discuss this
