### ISSUE TITLE
Rewrite geometry.rs

### ISSUE THREAD

**Issue by alice-i-cecile** [DioxusLabs/taffy#98]
Source: https://github.com/DioxusLabs/sprawl/blob/main/src/geometry.rs

1. flex_start and flex_end aren't agnostic to reversed FlexDirection. This likely leads to complications elsewhere.
2. It's not at all clear why `Rect` / `Size` / `Point` is generic over `T`, if it's only ever used with an `f32`.
3. There is no guarantee that left < right, or bottom < top
4. The fields are called `start` and `end`, rather than the more consistent `left` and `right`.
5. No unit tests are present.
6. `map` and `zip_size` seem over-engineered.
7. Size::undefined is horrible. See #83.
8. I kind of just want to store Size and Layout
9. `Size::zero` and `Point::zero` should be associated constants.

**Comment by TimJentzsch** [comment]
`start` and `end` being independent from `left` and `right` is a deliberate decision by Flexbox to make it work better with rtl languages, see [this MDN documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Basic_Concepts_of_Flexbox#start_and_end_lines).

**Comment by mockersf** [comment]
> There is no guarantee that left < right, or bottom < top

Because this is not a guarantee, and left can be greater than right, it's valid

**Comment by mockersf** [comment]
> * It's not at all clear why `Rect` / `Size` / `Point` is generic over `T`, if it's only ever used with an `f32`.

It's used internally over a `f32`, but the public API uses them over `Dimension` which can be other things

**Comment by Weibye** [comment]
According to flexbox specifications, the correct terminology would be:

- `main-start`
- `main-end`
- `cross-start`
- `cross-end`
instead of `top,` `bottom,` `left,` `right`, since that is direction agnostic in both axis.

I appreciate that we have a mix of both, but I suspect the previous authors never planned for direction agnosticism around the vertical axis. 

![image](https://user-images.githubusercontent.com/13300393/172944850-10e1f014-5837-40a5-99a1-1134e17ae7d9.png)

https://www.w3.org/TR/css-flexbox-1/#box-model

**Comment by alice-i-cecile** [comment]
Closing out in favor of the more actionable issues this generated.
